name: fruits_env
channels:
  - intel
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - codecov
  - sqlalchemy
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - tensorboard
  - pandas
  - pip
  - matplotlib
  - Flask
  - twilio
  - pip:
    - pyyaml
    - munch
    - pymysql