version: '3.7'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fruits_db_ctnr
    restart: always
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: fruits123
      MYSQL_DATABASE: "fruits_db"
      MYSQL_USER: "fruits_user"
      MYSQL_PASSWORD: "fruits123"
      MYSQL_PORT: 23306
    volumes:
      - ./schemas:/var/lib/mysql:rw
      - ./fruits:/tmp/fruits
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
  fruits: {}

networks:
  mysql_network:
    name: mysql_net
    driver: bridge
