version: '3.7'

services:

  db:
    #image: mysql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fruits_db_ctnr
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: fruits123
      MYSQL_DATABASE: "fruits_db"
      MYSQL_USER: "fruits_user"
      MYSQL_PASSWORD: "fruits123"
      MYSQL_PORT: 23306
    volumes:
      - ./schemas:/var/lib/mysql:rw
      - ./fruits:/tmp/fruits
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080